name : samplecmd
cmdname : samplecmd
summary : awesome sample
description : Just a sample application. Just a sample application.
version : 0.0.0
changelog : New feature
url : https://github.com/greymd/quick-linux-package-builder
author : Hello, World
email : sample@example.com
